version: '3.8'

services:
  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - airline-company-microservice
      - flight-microservice
      - passenger-microservice

  airline-company-microservice:
    build:
      context: ./airline-company-microservice
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    depends_on:
      - mongodb

  flight-microservice:
    build:
      context: ./flight-microservice
      dockerfile: Dockerfile
    ports:
      - "3002:3002"
    depends_on:
      - mongodb

  passenger-microservice:
    build:
      context: ./passenger-microservice
      dockerfile: Dockerfile
    ports:
      - "3003:3003"
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
